import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Card from '@mui/material/Card';
import CardContent from '@mui/material/CardContent';
import CardMedia from '@mui/material/CardMedia';
import Typography from '@mui/material/Typography';
import { CardActionArea } from '@mui/material';

export default function Home() {
    return (
        <div className="bg-zinc-900 text-white min-h-screen ">
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>

            <main className={'container m-auto px-4'}>

                <div className="flex justify-center  pt-32 mb-12">
                    <div className="profile  flex flex-wrap justify-center  items-center">
                        <img className={'rounded-full mr-8 h-56 w-56'} src="./avatar.jpg" alt=""/>
                        <div className="">
                            <h2 className={'text-4xl font-bold mb-6' +
                                ''}>Daniil Shumilov</h2>
                            <ul className="profileContacts">
                                <li><a
                                    className={'bg-blue-500 hover:bg-blue-400 text-white font-bold py-2 px-4 border-b-4 border-blue-700 hover:border-blue-500 rounded inline-flex mb-2.5'}
                                    href="https://t.me/daniil_shum">telegram</a></li>
                                <li><a
                                    className={'bg-blue-500 hover:bg-blue-400 text-white font-bold py-2 px-4 border-b-4 border-blue-700 hover:border-blue-500 rounded inline-flex mb-2.5'}
                                    href="mailto:shumilov.daniil.s@gmail.com">shumilov.daniil.s@gmail.com</a></li>
                                <li><a
                                    className={'bg-blue-500 hover:bg-blue-400 text-white font-bold py-2 px-4 border-b-4 border-blue-700 hover:border-blue-500 rounded inline-flex mb-2.5'}
                                    href="">CV</a></li>
                            </ul>
                        </div>
                    </div>
                </div>

                <h2 className={'text-center text-4xl font-bold mb-6'}>Projects</h2>

                <div className={'alert max-w-xl m-auto mb-10'} role="">
                    <div className="bg-red-500 text-white font-bold rounded-t px-4 py-2">
                        Внимание!
                    </div>
                    <div className="border border-t-0 border-red-400 rounded-b bg-red-100 px-4 py-3 text-red-700">
                        <p>Очень крутые работы, впечатлительным просьба уйти от экрана.</p>
                    </div>
                </div>
                <div className="cards flex justify-center">
                    <a href="https://github.com/shumilovDaniil/dns-clone" target="_blank" ><Card sx={{ maxWidth: 285}}>
                        <CardActionArea>
                            <CardMedia
                                component="img"
                                height="140"
                                image="/dns.png"
                                alt="project"
                            />
                            <CardContent>
                                <Typography gutterBottom variant="h5" component="div">
                                    DNS clone
                                </Typography>

                            </CardContent>
                        </CardActionArea>
                    </Card></a>
                </div>

            </main>

            <footer>

            </footer>
        </div>
)
}
